# Site
title:              Filosofía del Futuro
long_bio:           '¿Cuál es el rol de la filosofía en el siglo XXI? Es decir, en el siglo de mayor grado de desarrollo técnico y tecnológico de la historia, ¿Qué preguntas y herramientas propias de la filosofía nos sirven para pensar, discutir, orientar y criticar tanto el diseño de estas nuevas tecnologías como los rápidos avances que transversalmente se dan en las ciencias? ¿Qué conocimientos y discursos surgidos de las ciencias y las técnicas debemos estudiar, como filósofos, para poder llevar a cabo esta tarea?
Filosofía del Futuro es un colectivo interdisciplinario que trabaja a partir de estas preguntas. En esta interdisciplina se da el nexo entre las humanidades y las áreas de desarrollo técnico-científicas que permite tanto elaborar una filosofía más rica, que incorpore los conocimientos técnicos antes mencionados, como también facilitar el acercamiento filosófico a los problemas de investigación y diseño propios del conjunto de disciplinas enmarcadas en el campo de la ciencia y de la técnica.
En resumen, la propuesta es la siguiente: Llevar la pregunta filosófica a la vanguardia de la técnica.
'
description:        "Colectivo interdisciplinario para el desarrollo y la divulgación de la Filosofía del Futuro"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             es_US
url:                https://futurephilosophy.github.io
collections:
  authors:
    output: true
  publications:
    output: true
  scripts:
    output: true

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   futurephilosophy

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              filosofiayfuturo@gmail.com
# twitter:            username
# facebook:           username
github-url:         futurephilosophy
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          boid.ba
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
