# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:              Filosofía del Futuro
long_bio:           '¿Cuál es el rol de la filosofía en el siglo de mayor desarrollo técnico y tecnológico de la historia? Esta pregunta se despliega en otras dos: ¿Qué preguntas y herramientas propias de la filosofía nos sirven para pensar, discutir, orientar y criticar tanto el diseño de estas nuevas tecnologías como los rápidos avances que transversalmente se dan en las ciencias? y ¿Qué conocimientos y discursos surgidos de las ciencias y las técnicas debemos estudiar, como filósofos, para poder llevar a cabo esta tarea?<br /><br />Filosofía del Futuro es un colectivo interdisciplinario que trabaja a partir de estas preguntas. En esta interdisciplina se da el nexo entre las humanidades y las áreas de desarrollo técnico-científicas que permite tanto elaborar una filosofía más rica, que incorpore los conocimientos técnicos antes mencionados, como también facilitar el acercamiento filosófico a los problemas de investigación y diseño propios del conjunto de disciplinas enmarcadas en el campo de la ciencia y de la técnica.<br /><br />En resumen, la propuesta es la siguiente: llevar la pregunta filosófica a la vanguardia de la técnica.'
description:        "Colectivo interdisciplinario para el desarrollo y la divulgación de la Filosofía del Futuro"
reading_time:       true
words_per_minute:   300
logo:               'assets/img/title.png'
background:         'assets/img/placeholder-big.jpg'

permalink:          /:title/
locale:             es_AR
url:                https://filosofiadelfuturo.com

disqus_shortname:   futurephilosophy
email:              filosofiayfuturo@gmail.com
twitter_link:       https://twitter.com/filosofiaFuturo
github_link:        https://github.com/filosofiadelfuturo
instagram_link:     https://www.instagram.com/filosofiafuturo/
facebook_link:      https://www.facebook.com/filosofiadelfuturo

collections:
  authors:
    output: true
  publications:
    output: true
    permalink: /:title/
  scripts:
    output: true
    permalink: /:title/
  recommends:
    output: true
  cursoia:
    output: true
    permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-tagories
  
keep_files:
  - .git
  - .gitignore
  - CNAME

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - push.bat
  - TODO
